### ISSUE TITLE
confirm agenda for June workshop

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc-workshops#63]
The June agenda should follow a similar (but improved!) format as the may workshop, with morning talks and afternoon breakouts. 

We need to keep in mind that there is a concurrent "collaboration fest" and hackathon. Some workshop attendees will want to participate in the hackathon (to varying degrees) and others will not.

**Comment by ctb** [comment]
there is some interest in a more structured approach to at least some tracks - some people felt there were sessions they *had* to attend, and occasionally those sessions overlapped. I heard this the most from project managers. Maybe we could poll the PMs and ask.

ref [this comment](https://github.com/dib-lab/copper/issues/112#issuecomment-395549954)

I should say that I'm against too much upfront planning (as I think most of us are - unconferences and hallway tracks are great!), but some predefined structure might be good.

**Comment by StanAhalt** [comment]
What if we ask people to suggest topics now?

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by vmbrasseur** [comment]
One of the steps in the [unconferencing process](https://github.com/dcppc/dcppc-workshops/blob/master/intro_to_unconferencing.md), after all of the sessions have been placed on the schedule, is to stand back and review the schedule. This provides the opportunity to consolidate similar sessions, place logically related sessions next to each other on the schedule, and remove some conflicts. I wasn't at the May event so I don't know whether that step happened.

Regardless, we're never going to please everyone with a schedule. That's just the nature of conferences/collaborative events. To be honest, if we're doing our jobs properly then EVERY time slot will contain multiple sessions that people want to attend. 

As for proposing topics now: it's possible but usually does not usually work well in an unconference context. What typically happens is that the sessions suggested in advance often come from—shall we say—more _dynamic_ individuals. They end up trying to monopolise the schedule or otherwise control the content in a way that isn't conducive to effective collaboration. The emergent nature of unconferencing scheduling levels the playing field and encourages participation by a more diverse assortment of attendees.

However, on the feedback form someone suggested that we have unconference topic cards/sticky notes available during the lightning talks so they could write down session ideas that come to them during those initial talks. That's a really great idea and I think will help make the unconference breakout sessions more timely and effective.

(someone also suggested we have a map to make it easier to find the unconference breakout session rooms and I'm totally here for that idea)

**Comment by vmbrasseur** [comment]
It looks like @raynamharris has already posted an [agenda](http://nih-data-commons.us/2018-june-workshop/agenda) for the June workshop (no surprise; she's a force of nature), so I'm closing this.
