### ISSUE TITLE
Assessment mechanism?

### ISSUE THREAD

**Issue by vmbrasseur** [dcppc/dcppc-workshops#7]
We need a way for people to provide feedback to us about the workshops.

Since we'll need this in place before the May workshop, I'll drop this issue into that project.

**Comment by vmbrasseur** [comment]
Karen: …what exactly are we assessing?
@awz: NIH needs to see evidence of collaboration across teams. Serendipity between teams.

**Comment by karenword** [comment]
A very very proto-survey is here: https://ucdavis.co1.qualtrics.com/jfe/form/SV_43isVLx7nDYnOuN

**Comment by vmbrasseur** [comment]
Comments:

* Is that first question ("do you consent…") necessary? Isn't consent implied by taking the survey?
* Team or affiliation is a necessary question, IMO, if only to confirm we're getting participation across teams
* Page 3, the "usefulness" Likert questions: Could each option please use the same adjective, rather than changing from "useless" to "useful"? Something more like "Not at all useful", "Slightly useful", "Fairly useful" and "Very useful"?
* Page 3, the "usefulness" free text boxes: Maybe make these questions more general rather than focusing specifically on the usefulness? "Please common on the 5-minute overviews on Day 1". I think this will invite more comments.
* Page 4: Rather than "advice to the organizers," a more general, "What other feedback would you like to give to the organizers?" might be better. That opens it up both to comments as well as advice.
* Maybe add a bit of an NPS thing on there? "On a scale of 1 (nope, never) to 10 (hells yes), how likely are you to recommend this event to your team?" and then a free text with the question, "Why did you answer that way?" Actually, this could almost replace most of the usefulness stuff on Page 3 and make it a lot easier/quicker for people to get through the survey?

**Comment by karenword** [comment]
Excellent points, all! Thanks @vmbrasseur. Responses/updates are as follows:

- Consent is probably not necessary since this is strictly internal quality control. Should we, at some point, want to collect data for broader reporting, my understanding is that it would then be necessary (along with IRB approval or formal 'not-research' designation). It is nice to have the explanation about use & anonymity. I can take out the consent approval step if everyone agrees that's best for now.
- Usefulness questions: changed language as suggested
-  Re "advice" vs "other feedback" -- "advice" gives people a modicum of permission to be critical, which can be helpful. Also applying parallel language with the question about advice for future attendees has the small benefit of placing everyone's roles on the same plane. There is also a catch-all question for "anything else you'd like to tell us" which would be somewhat more redundant with "other feedback" to organizers. That being said, I don't have strong opinions here, so if anyone does, I'm happy to move on this.
-  I have added a "would you recommend" question. I think we could convert this to a 1-10 scale once we start targeting the broader community and are really concerned about splitting hairs between active and passive promoters? In the mean time I've added a simpler yes/no. As for replacing the usefulness questions I do think it's best to split the workshop into sections for examination. Also "useful" isn't quite the same thing as recommending... it is a component but people are usually also thinking about enjoyment & hassle etc. when balling into a recommendation. It's worthwhile to ask both! BUT easier/quicker IS important. I think this is about a 5-7 minute survey at present, so we can think keep thinking about this & other cuts.

- Finally (and not related to the comments above) I noticed a stated goal in the invitation of "surfacing hidden issues" so I added a question about whether they had discovered any new problems or obstacles, after the discovery of new tools or ideas, and added a "please explain" to both of those questions.

**Comment by vmbrasseur** [comment]
Suggestions from @raynamharris: 

* If the survey will be anonymous, we'll want to remove the Team/Affiliation question.
* We need to show NIH we're promoting collaboration. Is there a way we can capture that somehow? 

Suggestion from VMB: Add a "if we can contact you…" thing in there

Suggestion from @swzCuroverse: Increase the size of the "please explain" box

**Comment by karenword** [comment]
How about this for collaboration questions:
"Our team is better connected to other teams in the data commons as a result of this workshop." (Strongly disagree -> Strongly agree)
"Did you develop any plans to connect or communicate across KCs in a new way during this workshop?" (Definitely not -> Definitely) (could also add "Please tell us about your plans"... this diminishes anonymity but so do most of the "explain" prompts, to some extent.)

**Comment by karenword** [comment]
OK - I added "(Optional)" to all of the "please tell us about" questions to make it clear that people can choose to preserve their anonymity by withholding those details. 

I filled in the team/affiliation categories and added a "What KC do you work on?" -- both labeled Optional. Also added a "May we contact you" question.

I *think* this is ready to go! Let me know if there are any more changes to be made. @raynamharris would you be ok with administering this during the closing hours of the workshop so we can get a full set of responses?

**Comment by raynamharris** [comment]
I administered the survey during at about right after the final breakout and just before the final recaps and closing arguments. It was kinda nice to be in a quiet room (minus the sound of 40 type typing) for 5 minutes. 

I'll close this issue now but add reviewing the responses to the post-mortem https://github.com/dcppc/dcppc-workshops/issues/19
